name: build
on:
  workflow_call:
    inputs:
      docs:
        required: false
        type: boolean

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.102
      - uses: actions/cache@v1
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: ${{ runner.os }}-nuget
      - name: build
        run: |
          dotnet restore --locked-mode
          dotnet build --no-restore --configuration Release
      - name: docs
        if: inputs.docs
        uses: nikeee/docfx-action@v1.0.0
        with:
          args: ./docs/docfx.json
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: |
            ./src
            ./test
          key: ${{ github.sha }}
      - uses: actions/cache@v2
        if: inputs.docs
        id: restore-docs
        with:
          path: ./docs/dist
          key: ${{ github.sha }}
