name: build
on:
  workflow_call:

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: ${{ runner.os }}-nuget
      - name: build
        run: |
          dotnet restore --locked-mode
          dotnet build --no-restore --configuration Release
      - uses: actions/cache@v2
        with:
          path: |
            ./src/*/bin
            ./src/*/obj
            ./test/*/bin
            ./test/*/obj
          key: build-${{ github.sha }}
