name: docs

on:
  release:
    types: [released]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  generate:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: ${{ runner.os }}-nuget
      - uses: actions/cache@v2
        with:
          path: |
            ./src/*/bin
            ./src/*/obj
            ./test/*/bin
            ./test/*/obj
          key: build-${{ github.sha }}
      - name: generate
        uses: nikeee/docfx-action@v1.0.0
        with:
          args: ./docs/docfx.json
      - name: publish
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: ./docs/dist
      - uses: actions/upload-artifact@v2
        with:
          name: docs
          path: ./docs/dist
