name: docs

on:
  release:
    types: [released]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      docs: true

  docs:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.102
      - uses: actions/cache@v2
        id: restore-docs
        with:
          path: ./docs/dist
          key: ${{ github.sha }}
      - name: publish
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: ./docs/dist
      - name: artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: docs
          path: ./docs/dist
