name: docs
on:
  release:
    types: [released]
  workflow_dispatch:
    inputs: 
      orphan:
        type: boolean
        required: true
        default: false
        description: "Whether to erase git history of docs"

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  generate:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: ${{ runner.os }}-nuget
      - name: setup
        run: choco install docfx -y
      - name: generate
        run: docfx ./docs/docfx.json
      - uses: actions/upload-artifact@v2
        with:
          name: docs-${{ github.ref_name }}
          path: ./docs/dist

  publish:
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: docs-${{ github.ref_name }}
          path: ./docs/dist
      - name: publish
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: ./docs/dist
          single-commit: ${{ inputs.orphan }}
