name: main
on:
  push:
    branches:
      - main
      - develop
      - "fix/*"
      - "release/*"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
  pull_request:
  schedule:
    - cron: "00 6 * * 1" # Run every monday at 6:00 AM
  workflow_dispatch:
    inputs:
      scan:
        type: boolean
        description: Run CodeQL
        required: false
        default: false

jobs:
  build:
    uses: ./.github/workflows/build.yml

  test:
    needs: build
    uses: ./.github/workflows/test.yml
    with:
      pr: ${{ github.event.number || 0 }}

  scan:
    if: (github.event_name != 'push' || startsWith(github.ref, 'refs/tags/v')) && (github.event_name != 'workflow_dispatch' || github.event.inputs.scan)
    needs: build
    uses: ./.github/workflows/scan.yml
    permissions: 
      security-events: write

  package:
    needs: test
    uses: ./.github/workflows/package.yml

  release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    needs: 
      - package
      - scan
    uses: ./.github/workflows/release.yml
    permissions:
      contents: write
      packages: write
    secrets:
      NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
