name: scan
on:
  workflow_call:

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.102
      - uses: github/codeql-action/init@v1
        with:
          languages: csharp
      - uses: actions/cache@v1
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: ${{ runner.os }}-nuget
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: |
            ./src
            ./test
          key: ${{ github.sha }}
      - name: codeql
        run: github/codeql-action/analyze@v1
